### ISSUE TITLE
yarn start  运行  example\tuya-components-styled 使用 ios 手机加载时出差

### ISSUE THREAD

**Issue by skylli** [tuya/tuya-panel-kit#185]
## 组件
 
组件名称： tuya-panel-kit

## 版本

- 组件版本：
- react 版本："16.8.3",
- react-native 版本："0.59.10",
- node: 10.24.0

## 概述
使用 ios 手机加载时出差运行 《Test-涂鸦面板-RN》扫描加载页面时出错。

transform[stderr]: openssl config failed: error:25078067:DSO support routines:win32_load:could not load the shared library
transform[stderr]: ed: error:25078067:DSO support routines:win32_load:could not load the shared library
error: bundling failed: Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `D:\prj\tuya\tuya-panel-kit-master\packages\tuya-panel-kit\src\index.js`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\prj\tuya\tuya-panel-kit-master\example\tuya-components-styled\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 BUNDLE  [ios, dev] ./index.ios.js ▓░░░░░░░░░░░░░░░ 6.3% (1/108), failed.

transform[stderr]: Browserslist: caniuse-lite is outdated. Please run:
transform[stderr]: npx browserslist@latest --update-db
Bug 问题概述

## 重现步骤

1. cd tuya-panel-kit-master\example\tuya-components-styled  && yarn install && yarn start
2. ios 手机运行 
3. 《Test-涂鸦面板-RN》扫描加载 tuya-components-styled 页面

**Comment by ZengBeauty** [comment]
您好，参考一下这个解决办法：https://stackoverflow.com/questions/52486219/unable-to-resolve-module-babel-runtime-helpers-interoprequiredefault
